### ISSUE TITLE
frozenList wrongly compiled

### ISSUE THREAD

**Issue by rashtao** [azuqua/cassanknex#17]
This [test](https://github.com/azuqua/cassanknex/blob/develop/tests/columnFamily.test.js#L109) has a wrong assertion:

```js
frozenList("anyTypeListColumn", "anyType")
```

should be compiled to:

```text
"anyTypeListColumn" LIST <FROZEN <anyType>>
```

but currently it compiles to:

```text
"anyTypeListColumn" FROZEN <LIST <anyType>>
```

**Comment by UnbounDev** [comment]
@rashtao thanks for catching these! Fixed and deployed (v1.7.1).
