### ISSUE TITLE
access the raw driver

### ISSUE THREAD

**Issue by rashtao** [azuqua/cassanknex#25]
With `.getClient()` the already connected client is returned. Is there a way to get the static / raw driver? I mean the object returned by `require('cassandra-driver')`.

Eg. I often do:

```js
var TimeUuid = require('cassandra-driver').types.TimeUuid;
// ...
```

but I would not access the Cassandra Driver in this way (I could have mismatches between my and Cassankenx versions). It would be nice something like:

```js
var TimeUuid = require('cassanknex').driver.types.TimeUuid;
// ...
```

**Comment by UnbounDev** [comment]
:+1: makes sense!
