### ISSUE TITLE
How to count?

### ISSUE THREAD

**Issue by ezsper** [azuqua/cassanknex#30]
```
qb("keyspace")
  .count('*')
  .where("id", "=", id)
  .limit(1)
  .from("database")
  .exec({ prepare: true })
```

`.count is not a function`

**Comment by UnbounDev** [comment]
At long last, this is provided in `v1.16.0`; an example:
```
qb("keyspace")
  .select()
  .count('*')
  .where("id", "=", id)
  .limit(1)
  .from("database")
  .exec({ prepare: true })
```
**NB!** I highly recommend reviewing documentation on the `count` function in Cassandra as it has the potential to severely affect cluster performance (unless you happen to be using DSE Search against a Solr Core, in which case Solr is performing the count operation via Lucene indexes).

Ref: https://www.datastax.com/dev/blog/counting-keys-in-cassandra
> ...under the hood this is what the ‘select count’ query does too (with large enough limit).
