### ISSUE TITLE
the composite partition key syntax is incorrect when multiple cluster keys are used

### ISSUE THREAD

**Issue by batwicket** [azuqua/cassanknex#35]
When an array is specified for the cluster key arguments an extra parenthesis is placed around them in the PRIMARY KEY clause i.e., from https://docs.datastax.com/en/cql/3.1/cql/cql_reference/refCompositePk.html:
```
CREATE TABLE Cats (
  block_id uuid,
  breed text,
  color text,
  short_hair boolean,
  PRIMARY KEY ((block_id, breed), color, short_hair)
);
```

is, instead:
```
CREATE TABLE Cats (
  block_id uuid,
  breed text,
  color text,
  short_hair boolean,
  PRIMARY KEY ((block_id, breed), (color, short_hair))
);
```

The unit tests don't appear to catch this case. Sounds valid?

**Comment by UnbounDev** [comment]
Hello @batwicket,

I think the case you're referring to is handled by [this unit test]( https://github.com/azuqua/cassanknex/blob/master/tests/columnFamily.test.js#L52-L65). 

As to your second example I'm not certain what you mean as that is an invalid CQL statement:
```cqlsh
cqlsh:sandbox> CREATE TABLE Cats (
           ...   block_id uuid,
           ...   breed text,
           ...   color text,
           ...   short_hair boolean,
           ...   PRIMARY KEY ((block_id, breed), (color, short_hair))
           ... );
SyntaxException: line 6:34 no viable alternative at input '(' (... ((block_id, breed), [(]...)
```

**Comment by batwicket** [comment]
I may have been unclear. The second example I gave is the syntax produced by cassanknex. It adds extra parentheses around the cluster keys. As you say, this causes a syntax error.

**Comment by batwicket** [comment]
Just to be clear, I want to make sure I'm addressing something that's an issue. If it is then it might take me a few days to get to it if you don't have time.

**Comment by UnbounDev** [comment]
Ah, I see your point.

This statement is correct:
```
cassanKnex("cassanKnexy")
        .createColumnFamily("columnFamily")
        .text("textType")
        .uuid("uuidType")
        .int("intType")
        .timestamp("timestamp")
        .primary(["textType", "uuidType"], "timestamp", "intType");
```

But the following statement would produce additional brackets around the clustered columns:
```
cassanKnex("cassanKnexy")
        .createColumnFamily("columnFamily")
        .text("textType")
        .uuid("uuidType")
        .int("intType")
        .timestamp("timestamp")
        .primary(["textType", "uuidType"], ["timestamp", "intType"]);
```

Thanks for pointing it out, it's a nice convenience for input, I've added it to the next version push (#36)
