### ISSUE TITLE
Allow filtering

### ISSUE THREAD

**Issue by ndelvalle** [azuqua/cassanknex#41]
Is there a nice way to add the `ALLOW FILTERING` modifier to a query?

**Comment by ndelvalle** [comment]
Related: https://www.datastax.com/dev/blog/allow-filtering-explained-2

**Comment by UnbounDev** [comment]
Yes, via `allowFiltering()`; see the tests reference: https://github.com/azuqua/cassanknex/blob/master/tests/queries.test.js#L94-L104

**Comment by ndelvalle** [comment]
Awesome, thanks @UnbounDev !
Edit: I changed the issue title because it might seem rude
