### ISSUE TITLE
How can I handle streams backpressure?

### ISSUE THREAD

**Issue by idandagan1** [azuqua/cassanknex#71]
Hi,
Let's say I have an express app and I'd like to use streams.

for example:
```js
const express = require('express');
const app = express();

app.use((req, res, next) => {
  client.stream('SELECT time, val FROM temperature WHERE station_id=', [ 'abc' ])
    .on('readable', () => {
      let row;
      while (row = this.read()) {
         res.write(row); // THIS SHOULD BE PIPED
      }
    })
    .on('end', function () {})
    .on('error', function (err) {});
})
```

So in Node.js v10.0.0, they added support for [pipeline](https://nodejs.org/api/stream.html#stream_stream_pipeline_source_transforms_destination_callback) which uses the benefits of pipe for automatic pause/resume logic - but also forwarding errors and properly cleaning up streams if needed.

How can I handle backpressure?

**Comment by UnbounDev** [comment]
@idandagan1 that's a good question... the [cassandra-client docs](https://github.com/jorgebay/node-cassandra-cql#example-reading-the-whole-resultset-as-stream) only list examples similar to your own, but the [stream code](https://github.com/jorgebay/node-cassandra-cql/blob/2136de4cdde4219f9b4ba754a8f0c043077a83f2/lib/connection.js#L176-L190) *does* return a `ReadableStream` (actually a custom type that inherits from `stream.Readable`), so you'd think that it should be possible to include that type in a nodejs pipeline.

All that being said, there's some [interesting logic](https://github.com/jorgebay/node-cassandra-cql/blob/2136de4cdde4219f9b4ba754a8f0c043077a83f2/lib/types.js#L301-L325) going on w/ that custom type and I'm not certain if that would in some way inhibit your use case.

I would suggest two possible directions for the case:

1. Ask your question on the https://github.com/jorgebay/node-cassandra-cql repo and see if someone has figured this out for express+pipelines+cassandra-client.
2. As a work around, it may be possible to create a helper function that wraps the cassandra-client `stream` method, creating and returning a stream for use in your express response pipeline (I've tended to use [highland](https://caolan.github.io/highland/) as a utility for this type of thing).

**Comment by idandagan1** [comment]
I eventually used directly cassandra client:

```js
  const cassanknex = require('cassanknex');
  const cassandraClient = cassanknex.getClient();
  
  cassandraClient.stream('SELECT * FROM table', { prepare: true });
```
