### ISSUE TITLE
Update cassandra-driver version or make it a peer dependency

### ISSUE THREAD

**Issue by bhoudu** [azuqua/cassanknex#87]
Hello, I actually like cassanknex which I use mostly to generate CQL statements (which it is good for) before sending the requests to AWS Keyspaces which is a bit different to Datastax Cassandra.

As I don't use the cassandra-driver part, I think it would be better for users like me to just exclude this part, or to put it as peer dependency (I use latest driver 4.6.4 with aws SIG V4 additionnal library). Would it be better to declare it this way? Or is there any chance to update to the latest cassandra-driver version? Thanks.

**Comment by austinbrown-okta** [comment]
Hi @bhoudu, thanks for the ping on this, I know a few use cases where having the driver installed w/ the package makes things easier (especially for quickstart-style usage), but the driver upgrade makes sense!

Added a PR for this here: https://github.com/azuqua/cassanknex/pull/88

**Comment by austinbrown-okta** [comment]
`cassandra-driver` is updated and available in `v2.0.0` of the npm package: https://www.npmjs.com/package/cassanknex?activeTab=versions
